# -*- coding: utf-8 -*-
"""polynomial_run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1erJeMgVHQ5C3ZlmLFsKsDh2E3Xj2bWYL
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import csv

# train_dataset = pd.read_csv(
#     "/content/1_train.csv", delimiter=",")

# test_dataset = pd.read_csv(
#     "/content/1_test.csv", delimiter=",")

# fine_dataset = pd.read_csv(
#     "/content/model_x.csv", delimiter=",")

train_dataset = pd.read_csv(
    "test_train/1_train.csv.csv", delimiter=",")

test_dataset = pd.read_csv(
    "test_train/1_test.csv", delimiter=",")

fine_dataset = pd.read_csv(
    "test_train/model_x.csv", delimiter=",")


X_train = train_dataset['d']
X_train = np.asarray(X_train)
y_train = train_dataset['w']
y_train = np.asarray(y_train)

X_test = test_dataset['d']
X_test = np.asarray(X_test)
y_test = test_dataset['w']
y_test = np.asarray(y_test)

X_fine = fine_dataset['d']
X_fine = np.asarray(X_fine)

ws_all = []
y_pred_all_test = []
y_pred_all_train = []
y_fine_all = []


for i in range(2, 16):
    print(f"degree={i}:")
    ws = []
    poly = PolynomialFeatures(degree=i, include_bias=False)
    X_poly_train = poly.fit_transform(X_train.reshape(-1, 1))
    polyReg = LinearRegression().fit(X_poly_train, y_train.reshape(-1, 1))
    y_predict_train = polyReg.predict(X_poly_train)

    X_poly_test = poly.fit_transform(X_test.reshape(-1, 1))
    y_predict_test = polyReg.predict(X_poly_test)

    X_poly_fine = poly.fit_transform(X_fine.reshape(-1, 1))
    y_predict_fine = polyReg.predict(X_poly_fine)

    w0 = polyReg.intercept_
    w = polyReg.coef_
    ws = np.append(w0, w)

    with open('1_train_predict.csv', 'a') as f:
        # using csv.writer method from CSV package
        write = csv.writer(f)
        write.writerow(y_predict_train)

    with open('1_test_predict.csv', 'a') as f:
        # using csv.writer method from CSV package
        write = csv.writer(f)
        write.writerow(y_predict_test)

    with open('1_fine_predict.csv', 'a') as f:
     # using csv.writer method from CSV package
        write = csv.writer(f)
        write.writerow(y_predict_fine)

    with open('1_ws_all.csv', 'a') as f:
     # using csv.writer method from CSV package
        write = csv.writer(f)
        write.writerow(ws)
